/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurBall: typeof import('./src/components/common/BlurBall.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/Toolbar/DarkModeSwitch.vue')['default']
    DropDown: typeof import('./src/components/common/DropDown/DropDown.vue')['default']
    DropDownItem: typeof import('./src/components/common/DropDown/DropDownItem.vue')['default']
    DropDownMenu: typeof import('./src/components/common/DropDown/DropDownMenu.vue')['default']
    DynamicSVG: typeof import('./src/components/common/DynamicSVG.vue')['default']
    ICarbonUserAvatar: typeof import('~icons/carbon/user-avatar')['default']
    'IEosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
    'IIc:twotoneDarkMode': typeof import('~icons/ic/twotone-dark-mode')['default']
    'IIc:twotoneLightMode': typeof import('~icons/ic/twotone-light-mode')['default']
    'IIon:language': typeof import('~icons/ion/language')['default']
    'IIon:logoAppleAr': typeof import('~icons/ion/logo-apple-ar')['default']
    'IMdi:closeCircleOutline': typeof import('~icons/mdi/close-circle-outline')['default']
    'IMdi:eyeOffOutline': typeof import('~icons/mdi/eye-off-outline')['default']
    'IMdi:eyeOutline': typeof import('~icons/mdi/eye-outline')['default']
    'IMingcute:downLine': typeof import('~icons/mingcute/down-line')['default']
    NeumorphismButton: typeof import('./src/components/neumorphism/NeumorphismButton.vue')['default']
    NeumorphismCheckbox: typeof import('./src/components/neumorphism/NeumorphismCheckbox.vue')['default']
    NeumorphismInput: typeof import('./src/components/neumorphism/NeumorphismInput.vue')['default']
    NeumorphismLink: typeof import('./src/components/neumorphism/NeumorphismLink.vue')['default']
    NeumorphismSwitch: typeof import('./src/components/neumorphism/NeumorphismSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/common/Toolbar/ToolBar.vue')['default']
    TranslateDropDown: typeof import('./src/components/common/Toolbar/TranslateDropDown.vue')['default']
    TypedText: typeof import('./src/components/common/TypedText.vue')['default']
  }
}
