/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ICarbonUserAvatar: typeof import('~icons/carbon/user-avatar')['default']
    'IDashicons:restApi': typeof import('~icons/dashicons/rest-api')['default']
    'IFlowbite:fileExportSolid': typeof import('~icons/flowbite/file-export-solid')['default']
    'IFlowbite:fileImportSolid': typeof import('~icons/flowbite/file-import-solid')['default']
    'IFluent:flow32Filled': typeof import('~icons/fluent/flow32-filled')['default']
    'IIc:roundApi': typeof import('~icons/ic/round-api')['default']
    'IIc:roundDashboard': typeof import('~icons/ic/round-dashboard')['default']
    'IIc:sharpLanguage': typeof import('~icons/ic/sharp-language')['default']
    'IIc:twotoneLanguage': typeof import('~icons/ic/twotone-language')['default']
    IIcon: typeof import('~icons/ic/on')['default']
    'IIconoir:db': typeof import('~icons/iconoir/db')['default']
    'IIconParkSolid:api': typeof import('~icons/icon-park-solid/api')['default']
    'IMaterialSymbols:database': typeof import('~icons/material-symbols/database')['default']
    'IMaterialSymbols:databaseOutline': typeof import('~icons/material-symbols/database-outline')['default']
    'IMaterialSymbols:storageRounded': typeof import('~icons/material-symbols/storage-rounded')['default']
    'IMdi:file': typeof import('~icons/mdi/file')['default']
    'IMingcute:layoutFill': typeof import('~icons/mingcute/layout-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
