/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurBall: typeof import('./src/components/common/BlurBall.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/Toolbar/DarkModeSwitch.vue')['default']
    DropDown: typeof import('./src/components/common/DropDown/DropDown.vue')['default']
    DropDownItem: typeof import('./src/components/common/DropDown/DropDownItem.vue')['default']
    DropDownMenu: typeof import('./src/components/common/DropDown/DropDownMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ICarbonUserAvatar: typeof import('~icons/carbon/user-avatar')['default']
    'IDashicons:restApi': typeof import('~icons/dashicons/rest-api')['default']
    'IFlowbite:fileExportSolid': typeof import('~icons/flowbite/file-export-solid')['default']
    'IFlowbite:fileImportSolid': typeof import('~icons/flowbite/file-import-solid')['default']
    'IFluent:flow32Filled': typeof import('~icons/fluent/flow32-filled')['default']
    'IIc:roundApi': typeof import('~icons/ic/round-api')['default']
    'IIc:roundDashboard': typeof import('~icons/ic/round-dashboard')['default']
    'IIc:sharpLanguage': typeof import('~icons/ic/sharp-language')['default']
    'IIc:twotoneDarkMode': typeof import('~icons/ic/twotone-dark-mode')['default']
    'IIc:twotoneLightMode': typeof import('~icons/ic/twotone-light-mode')['default']
    'IIconParkSolid:api': typeof import('~icons/icon-park-solid/api')['default']
    'IIon:language': typeof import('~icons/ion/language')['default']
    'IMaterialSymbols:database': typeof import('~icons/material-symbols/database')['default']
    'IMaterialSymbols:storageRounded': typeof import('~icons/material-symbols/storage-rounded')['default']
    'IMdi:file': typeof import('~icons/mdi/file')['default']
    'IMingcute:downLine': typeof import('~icons/mingcute/down-line')['default']
    'IMingcute:layoutFill': typeof import('~icons/mingcute/layout-fill')['default']
    NeumorphismButton: typeof import('./src/components/neumorphism/NeumorphismButton.vue')['default']
    NeumorphismInput: typeof import('./src/components/neumorphism/NeumorphismInput.vue')['default']
    NeumorphismSwitch: typeof import('./src/components/neumorphism/NeumorphismSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/common/Toolbar/ToolBar.vue')['default']
    TranslateDropDown: typeof import('./src/components/common/Toolbar/TranslateDropDown.vue')['default']
    TypedText: typeof import('./src/components/common/TypedText.vue')['default']
  }
}
